api_dwh:

  target: dev

  outputs:

    dev:
      type: postgres
      host: 192.168.10.120
      user: postgres
      password: Admin@postgres123
      port: 5432
      dbname: warehouse
      schema: mart
      threads: 1