#just for tac
statistics=true
job=test
jobVersion=0.1
date=2026-05-05 081559367
contextName=Default
jobId=_NaXvIAYwEfGCHrnkjUZYXQ
jobType=Standard
framework=
projectId=0
applyContextToChildren=false
project=LOCAL_PROJECT
branch=branches/
cmdLineVersion=8.0.1.20211109_1610
gitAuthor=
gitCommitId=
gitCommitDate=